using Test
using ParameterSpace

rm(joinpath(@__DIR__, "output"), recursive=true)
mkoutputdir(joinpath(@__DIR__, "output"))

include("test_datacore.jl")
include("test_constraint.jl")
include("test_constraints.jl")
include("test_experiment.jl")
include("test_dataset.jl")
include("test_dataio.jl")
include("test_coverage.jl")
include("test_gaps.jl")
include("test_paramdim.jl")
include("test_paramspace.jl")
include("test_coupled.jl")
include("test_sampling_abstract.jl")
include("test_sampling_random.jl")
include("test_sampling_lhs.jl")
include("test_sampling_sobol.jl")
include("test_sampling_grid.jl")
include("test_mask.jl")
include("test_config_yaml.jl")
include("test_config_toml.jl")
include("test_analyse_function.jl")
include("test_analyse_program.jl")
include("test_parallel_threads.jl")
include("test_compat.jl")
